### ISSUE TITLE
请教FAST_LIO中禾赛雷达和9轴imu的问题

### ISSUE THREAD

**Issue by 1137472490** [JokerJohn/JokerJohn#4]
大佬，您好，有个问题想请教一下。我看到您的激光雷达是禾赛PandarXT-32线，我现在也是采用这款激光雷达，加一个维特的（9 轴 MEMS），我发现禾赛的这款雷达存在坐标系90度偏移以及它的时间戳和ros中的时间不统一问题，然后目前我发现针对LIO-SAM以及Fast-lio的改进并没有加入禾赛雷达的支持，我看到您已经跑好了LIO-SAM和Fast-lio算法，并且修改了代码加入了禾赛雷达的格式，就说明您已经标定好了雷达和IMU之间的外参数据，并且配置了LIO-SAM和Fast-lio算法，我目前搜寻了网上的资料发现了您，请问能否有幸获取下您的修改代码，以及指导下如何标定禾赛雷达和IMU之间的数据呢，如果您觉得知识付费我们可以细聊吗？求助，我是用作学术实验以及个人研究，麻烦您了，看到回复！谢谢！

**Comment by JokerJohn** [comment]
@JokerJohn 
Hello，感谢关注。
禾赛的雷达默认坐标系定义是与velodyne这些不一样的，但经过外参转换到IMU body系后都是一样的，我们其实不需要关注这个。禾赛的时间戳定义时，保存的是每个点的绝对时间，并不是相对于这一帧点云起时的时间（相对时间），而在传统的LIO算法中一般都使用的是相对时间。我在[PALoc](https://github.com/JokerJohn/PALoc/blob/main/paloc/src/fastlio/preprocess.cpp)中适配了禾赛雷达的FAST-LIO代码，你可以看下这部分代码。可以看到这部分计算每个点相对于这一帧起时时刻的相对时间如下，单位为s，FAST LIO2中要求单位为ms，可以打印出每个点的时间戳最后在0-100ms内即为正确的。
<img width="578" alt="image" src="https://github.com/user-attachments/assets/6e35a30a-e482-4a8d-81e2-fa9483220055" />
同样[LIO-SAM-6AXIS](https://github.com/JokerJohn/LIO_SAM_6AXIS/blob/main/LIO-SAM-6AXIS/src/imageProjection.cpp)中我也进行了适配，主要问题还是时间戳，单位为s。最后一行，点的相对时间戳=当前时间-起始点时间。
<img width="566" alt="image" src="https://github.com/user-attachments/assets/f530581f-8105-4cb1-87f8-4bfb3d0eb00a" />
HILTI- Oxford数据集也是采用这款雷达，你可以下载数据进行测试。

**Comment by 1137472490** [comment]
十分感谢您的回复，我看到了您的PALoc算法，我将先拜读您的论文以后，我再对您的源码中关于PandarXT-32的部分进行研究，感谢，希望后续能继续向您咨询，还望不吝赐教
